### ISSUE TITLE
Add HTTPS support to aspinsiders.com

### ISSUE THREAD

**Issue by augustoproiete** [aspinsiders/aspinsiders.com#24]
GitHub recently [announced support for HTTPS on custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) hosted on GitHub Pages by partnering with [Let's Encrypt](https://letsencrypt.org) who issues the certificates.

We can benefit from that and in order to support HTTPS we just need to change the `A` records in the DNS settings for our domain.

@ardalis, could you please:

1. Delete all existing `A` records for `aspinsiders.com`

2. Add the 4 (four) `A` records below to `aspinsiders.com`
* `185.199.108.153`
* `185.199.109.153`
* `185.199.110.153`
* `185.199.111.153`

More detailed instructions [here](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider) if you need.

---

ps: Please, let me know when it's done, so I can flip the switch on the GitHub settings for HTTPS.

**Comment by ardalis** [comment]
Done:
![image](https://user-images.githubusercontent.com/782127/40803702-46ff7d42-64e7-11e8-842c-4c7cb8f29c48.png)

**Comment by augustoproiete** [comment]
Thanks @ardalis!

HTTPS set up for [aspinsiders.com](http://aspinsiders.com) and enforced.

![image](https://user-images.githubusercontent.com/177608/41010081-d7eac83e-690b-11e8-99e4-9ec09d020002.png)
